# Generated by Django 5.0.6 on 2024-07-07 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_requisito', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=30)),
                ('apellido_estudiante', models.CharField(max_length=30)),
                ('correo_estudiante', models.EmailField(max_length=60)),
                ('fecha_nacimiento', models.DateField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrera.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='EstudiantePorRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_cumplido', models.BooleanField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.requisito')),
            ],
        ),
    ]
